name: Update GitHub Activity

on:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  update-gh-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
